name: trading_module
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.1
  intl: ^0.17.0
  syncfusion_flutter_pdfviewer: ^19.4.54-beta
  json_annotation: ^4.4.0
  math_expressions: ^2.3.0
  auto_size_text: ^3.0.0
  flutter_svg: ^0.23.0+1
  get_storage: ^2.0.3
  pin_code_fields: ^7.3.0
  pdfx: ^2.0.1+1
  share: ^2.0.4
  flutter_html: ^2.2.1
  path_provider: ^2.0.9
  package_info: ^2.0.2
  connectivity: ^3.0.6
  device_info_plus: ^3.2.1
  flutter_sticky_header: ^0.6.1
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  internet_file: ^1.0.0+2
  smooth_page_indicator: ^1.0.0+2
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  simple_tooltip: ^1.0.0
  flutter_custom_tabs: ^1.0.4
  universal_html: ^2.0.8
  animated_flip_counter: ^0.2.4
  sticky_headers: ^0.2.0
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  rxdart: ^0.27.4
  #  flutter_spinkit: ^4.1.2+1
  #  loading: ^1.0.2

  #  candlesticks: ^2.1.0
  http: ^0.13.4

  candlesticks:
    git:
      url: https://github.com/ducanh230397/candlesticks2.git
      ref: master
  firebase_core: ^1.16.0
  #flutter_client_sse: ^1.0.0
#  flutter_client_sse: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  lint: ^1.7.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/fonts/iCielHelveticaNowText/
    - assets/fonts/Nunito/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: iCielHelveticaNowText
      fonts:
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Thin.otf
          weight: 100
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Extralight.otf
          weight: 200
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Light.otf
          weight: 300
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Regular.otf
          weight: 400
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Medium.otf
          weight: 500
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Bold.otf
          weight: 700
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Extrabold.otf
          weight: 800
        - asset: assets/fonts/iCielHelveticaNowText/iCielHelveticaNowText-Black.otf
          weight: 900
    - family: iCielBCCubano
      fonts:
        - asset: assets/fonts/iCielBCCubano/iCielBCCubano-Normal.otf
          weight: 400